// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYQA66rKOPrb4kce-hYCTYAbGKanVGbZ8',
    appId: '1:1029530532506:web:2fa18cc521b2524e5afd23',
    messagingSenderId: '1029530532506',
    projectId: 'mirrorsbeautylounge-7c5ff',
    authDomain: 'mirrorsbeautylounge-7c5ff.firebaseapp.com',
    storageBucket: 'mirrorsbeautylounge-7c5ff.firebasestorage.app',
    measurementId: 'G-GMWQSDP9JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQA66rKOPrb4kce-hYCTYAbGKanVGbZ8',
    appId: '1:1029530532506:android:demo-app-id',
    messagingSenderId: '1029530532506',
    projectId: 'mirrorsbeautylounge-7c5ff',
    storageBucket: 'mirrorsbeautylounge-7c5ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYQA66rKOPrb4kce-hYCTYAbGKanVGbZ8',
    appId: '1:1029530532506:ios:demo-app-id',
    messagingSenderId: '1029530532506',
    projectId: 'mirrorsbeautylounge-7c5ff',
    storageBucket: 'mirrorsbeautylounge-7c5ff.firebasestorage.app',
    iosBundleId: 'com.example.mirrorsbeautylounge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYQA66rKOPrb4kce-hYCTYAbGKanVGbZ8',
    appId: '1:1029530532506:macos:demo-app-id',
    messagingSenderId: '1029530532506',
    projectId: 'mirrorsbeautylounge-7c5ff',
    storageBucket: 'mirrorsbeautylounge-7c5ff.firebasestorage.app',
    iosBundleId: 'com.example.mirrorsbeautylounge',
  );
}